version: '3'
services:
  backend:
    build: ./mern/backend
    ports:
      - "5051:5050"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5174:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5051

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
